### ISSUE TITLE
c-algorithms code quality

### ISSUE THREAD

**Issue by laoshaw** [fragglet/c-algorithms#38]
looking for c data structures and algorithms as my c tool kit, the recent release of c-algorithms is 8 years ago, is it actively maintained and 'production ready'? does it go  through lots of test cases and field use, or at this point it's more of a reference implementation for others to learn how to do data structure and algorithms coding in C?

**Comment by fragglet** [comment]
It's quite difficult to answer your question: I have had very few people
ever contact me to tell me that they are using the library in any capacity.
I also haven't seen any open source projects using it. It is possible that
there are companies out there using it internally in their products for all
I know.

However, I've also had very few bug reports despite the exposure that the
project has had (the project has a decent number of stars) so that is
perhaps a sign in its favour.

I can tell you that the test suite is very extensive; I aimed for 100%
coverage and certainly got very close. You can read about the approach to
testing here:

https://fragglet.github.io/c-algorithms/testing.html

**Comment by fragglet** [comment]
Closing issue but please feel free to continue discussion.
